import type { NextConfig } from "next";

// Auth requests are proxied through src/app/api/auth/[...path]/route.ts
// so Better Auth's trustedOrigins check receives a known-good Origin header.
const nextConfig: NextConfig = {
  async redirects() {
    return [
      {
        source: "/:path*",
        has: [{ type: "host", value: "lallifafa.com" }],
        destination: "https://www.lallifafa.com/:path*",
        permanent: true,
      },
    ];
  },

  async headers() {
    return [
      {
        source: "/(.*)",
        headers: [
          { key: "X-Content-Type-Options", value: "nosniff" },
          { key: "X-Frame-Options", value: "SAMEORIGIN" },
          { key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
          {
            key: "Permissions-Policy",
            value: "camera=(), microphone=(), geolocation=(), interest-cohort=()",
          },
          {
            key: "Content-Security-Policy",
            value: [
              "default-src 'self'",
              // GA4 + Google Ads (AW-*) + Meta Pixel scripts
              "script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://www.google-analytics.com https://googleads.g.doubleclick.net https://pagead2.googlesyndication.com https://www.googleadservices.com https://connect.facebook.net https://challenges.cloudflare.com",
              "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com",
              "font-src 'self' https://fonts.gstatic.com",
              // Meta Pixel noscript 1×1 + Google Ads measurement + remarketing pixels
              "img-src 'self' data: blob: https://*.convex.cloud https://*.convex.site https://www.google-analytics.com https://www.googletagmanager.com https://www.google.com https://www.google.co.in https://www.facebook.com https://googleads.g.doubleclick.net https://ad.doubleclick.net https://www.googleadservices.com",
              // GA4 regional endpoints + Google Ads conversion + remarketing + Meta Pixel beacon
              "connect-src 'self' https://*.convex.cloud https://*.convex.site https://www.google-analytics.com https://analytics.google.com https://region1.google-analytics.com https://www.googletagmanager.com https://www.google.com https://stats.g.doubleclick.net https://googleads.g.doubleclick.net https://ad.doubleclick.net https://www.googleadservices.com https://www.facebook.com https://connect.facebook.net https://api.razorpay.com wss://*.convex.cloud",
              "media-src 'self' blob: https://*.convex.cloud https://*.convex.site",
              "frame-src https://api.razorpay.com https://bid.g.doubleclick.net https://challenges.cloudflare.com",
              "object-src 'none'",
              "base-uri 'self'",
              "form-action 'self'",
            ].join("; "),
          },
        ],
      },
      {
        // Static brand assets served straight from /public (images, audio,
        // fonts) get Next's default short-lived cache otherwise. These are
        // versioned by filename change, not by content, so a long cache is
        // safe -- browsers/CDN just re-fetch once the URL itself changes.
        source: "/:path*.(jpg|jpeg|png|webp|avif|gif|svg|ico|woff|woff2|mp3)",
        headers: [
          { key: "Cache-Control", value: "public, max-age=604800, stale-while-revalidate=86400" },
        ],
      },
    ];
  },
  images: {
    // Next's own default deviceSizes ([640, 750, 828, ...]) has no entry
    // below 640 -- so any `fill` image using a viewport-relative `sizes`
    // (e.g. "100vw") on a ~375px mobile screen still gets served the 640px
    // variant, wasting ~30-40% of the transfer for nothing (confirmed via
    // real mobile PageSpeed: several homepage images requested at 640px
    // while rendering at 325-330px). Prepending mobile-appropriate
    // breakpoints lets those same `sizes` hints resolve to a properly
    // small image without touching every component.
    deviceSizes: [480, 640, 750, 828, 1080, 1200, 1920, 2048, 3840],
    remotePatterns: [
      // Convex storage (scene images generated by AI)
      {
        protocol: "https",
        hostname: "*.convex.cloud",
      },
      // Convex site HTTP actions (fallback)
      {
        protocol: "https",
        hostname: "*.convex.site",
      },
    ],
    // Default is 60s -- these are mostly static brand/marketing images that
    // change rarely, so the optimizer cache can safely live much longer.
    minimumCacheTTL: 604800,
  },
};

export default nextConfig;
