import type { NextConfig } from "next";

// Auth requests are proxied through src/app/api/auth/[...path]/route.ts
// so Better Auth's trustedOrigins check receives a known-good Origin header.
const nextConfig: NextConfig = {
  images: {
    remotePatterns: [
      // Convex storage (scene images generated by AI)
      {
        protocol: "https",
        hostname: "*.convex.cloud",
      },
      // Convex site HTTP actions (fallback)
      {
        protocol: "https",
        hostname: "*.convex.site",
      },
    ],
  },
};

export default nextConfig;
