"use client";

import { useState } from "react";
import { ChevronDown } from "lucide-react";

const faqs = [
  {
    q: "What age is Lalli Fafa for?",
    a: "Stories are crafted for all children — from toddlers (age 2+) who love listening to narration, to older kids who enjoy following along with the text. There's no ceiling. Our themes and lesson complexity adapt based on the age you set.",
  },
  {
    q: "How personalised are the stories really?",
    a: "Very. Your child's name, favourite colour, favourite animal, and gender are woven directly into the story — not just mentioned once, but used throughout. Lalli and Fafa refer to your child by name and react to their preferences. It genuinely feels like it was written just for them.",
  },
  {
    q: "Can I get stories in Hindi?",
    a: "Yes! Full Hindi narration with native-quality voices is available on all paid plans. English is available on all plans including free. More languages are on the roadmap.",
  },
  {
    q: "How long does it take to generate a story?",
    a: "Under 2 minutes from clicking 'Generate' to a fully narrated story with illustrations. The AI works on text, images, and voice simultaneously.",
  },
  {
    q: "Is there a free plan?",
    a: "Yes — sign up for free and get 250 welcome credits. You can generate multiple stories with no time limit on the free tier. Upgrade to the Magic Pass to unlock voice narration, AI illustrations, and longer story lengths.",
  },
  {
    q: "What AI technology powers the stories?",
    a: "Stories are written by OpenAI GPT-4o-mini using our custom story engine (3 narrative structures, 15+ lessons, 10+ themes). Illustrations are generated by Google Gemini 2.5 Flash. Narration uses ElevenLabs TTS with 4 distinct character voices.",
  },
  {
    q: "Can I use Lalli Fafa offline?",
    a: "Not yet — stories are generated live and require an internet connection. However, generated stories are saved to your library and can be replayed anytime.",
  },
  {
    q: "Is my child's data safe?",
    a: "Completely. We never share personal data. Stories are stored privately per account. We follow strict privacy practices and the platform contains no ads, no tracking pixels, and no third-party content.",
  },
  {
    q: "When is the physical shop launching?",
    a: "We're currently building our product range — activity kits, story boxes, and character merchandise. Sign up to be notified when they launch. Subscribers get early access and a discount.",
  },
];

function FAQItem({ q, a }: { q: string; a: string }) {
  const [open, setOpen] = useState(false);
  return (
    <div
      className="rounded-2xl overflow-hidden transition-all duration-200"
      style={{
        background: open ? "#fff" : "rgba(255,255,255,0.6)",
        border: open ? "1.5px solid rgba(26,191,166,0.3)" : "1.5px solid rgba(0,0,0,0.05)",
      }}
    >
      <button
        className="w-full flex items-center justify-between gap-4 p-5 text-left"
        onClick={() => setOpen(!open)}
      >
        <span
          style={{
            fontFamily: "'Baloo 2', sans-serif",
            fontWeight: 700,
            fontSize: "1rem",
            color: "var(--lf-dark)",
          }}
        >
          {q}
        </span>
        <ChevronDown
          size={20}
          className="flex-shrink-0 transition-transform duration-200"
          style={{
            color: "var(--lf-teal)",
            transform: open ? "rotate(180deg)" : "rotate(0deg)",
          }}
        />
      </button>
      {open && (
        <div className="px-5 pb-5">
          <p style={{ color: "rgba(45,45,45,0.7)", fontSize: "0.95rem", lineHeight: 1.7 }}>
            {a}
          </p>
        </div>
      )}
    </div>
  );
}

export function FAQSection() {
  return (
    <section className="py-20 lg:py-28" style={{ background: "var(--lf-mint)" }}>
      <div className="mx-auto px-6" style={{ maxWidth: 780 }}>
        {/* Header */}
        <div className="text-center mb-12 flex flex-col items-center gap-3">
          <h2
            style={{
              fontFamily: "'Baloo 2', sans-serif",
              fontSize: "clamp(2rem, 4vw, 3rem)",
              fontWeight: 800,
              color: "var(--lf-dark)",
            }}
          >
            Got questions?{" "}
            <span className="text-gradient-teal">We've got answers.</span>
          </h2>
        </div>

        {/* FAQ list */}
        <div className="flex flex-col gap-3">
          {faqs.map((faq, i) => (
            <FAQItem key={i} q={faq.q} a={faq.a} />
          ))}
        </div>
      </div>
    </section>
  );
}
