"use client";

import { useState } from "react";
import Link from "next/link";
import { ChevronDown, ArrowLeft, Sparkles } from "lucide-react";
import { SiteHeader } from "@/components/layout/SiteHeader";
import { SiteFooter } from "@/components/layout/SiteFooter";

const faqGroups = [
  {
    label: "Getting started",
    color: "var(--lf-sunshine)",
    bg: "rgba(255,193,7,0.12)",
    items: [
      {
        q: "What age is Lalli Fafa for?",
        a: "Stories are crafted for all children — from toddlers (age 2+) who love listening to narration, to older kids who enjoy following along with the text. Our themes and lesson complexity adapt based on the age you set in your child's profile.",
      },
      {
        q: "Is there a free plan?",
        a: "Yes — sign up for free and get 250 welcome credits. You can generate multiple stories with no time limit on the free tier. Upgrade to the Magic Pass to unlock voice narration, AI illustrations, and longer story lengths.",
      },
      {
        q: "How long does it take to generate a story?",
        a: "Under 2 minutes from clicking 'Generate' to a fully narrated story with illustrations. The AI works on text, images, and voice simultaneously so everything is ready together.",
      },
    ],
  },
  {
    label: "Stories & personalisation",
    color: "var(--lf-teal)",
    bg: "rgba(0,201,167,0.12)",
    items: [
      {
        q: "How personalised are the stories really?",
        a: "Very. Your child's name, favourite colour, favourite animal, and gender are woven directly into the story — not just mentioned once, but used throughout. Lalli and Fafa refer to your child by name and react to their preferences. It genuinely feels like it was written just for them.",
      },
      {
        q: "Can I get stories in Hindi?",
        a: "Yes! Full Hindi narration with native-quality voices is available on all paid plans. English is available on all plans including free. More languages are on the roadmap.",
      },
      {
        q: "Can I use Lalli Fafa offline?",
        a: "Not yet — stories are generated live and require an internet connection. However, generated stories are saved to your library and can be replayed anytime without regenerating.",
      },
    ],
  },
  {
    label: "Technology & safety",
    color: "var(--lf-electric)",
    bg: "rgba(124,77,255,0.1)",
    items: [
      {
        q: "What AI technology powers the stories?",
        a: "Stories are written by OpenAI GPT-4o-mini using our custom story engine (3 narrative structures, 15+ lessons, 10+ themes). Illustrations are generated by Google Gemini 2.5 Flash. Narration uses ElevenLabs TTS with 4 distinct character voices.",
      },
      {
        q: "Is my child's data safe?",
        a: "Completely. We never share personal data. Stories are stored privately per account. We follow strict privacy practices and the platform contains no ads, no tracking pixels, and no third-party content.",
      },
      {
        q: "When is the physical shop launching?",
        a: "We're currently building our product range — activity kits, story boxes, and character merchandise. Sign up to be notified when they launch. Subscribers get early access and a discount.",
      },
    ],
  },
];

function FAQItem({ q, a }: { q: string; a: string }) {
  const [open, setOpen] = useState(false);
  return (
    <div
      className="rounded-2xl overflow-hidden transition-all duration-200"
      style={{
        background: open ? "#fff" : "rgba(255,255,255,0.6)",
        border: open ? "1.5px solid rgba(0,201,167,0.3)" : "1.5px solid rgba(0,0,0,0.06)",
      }}
    >
      <button
        className="w-full flex items-center justify-between gap-4 p-5 text-left"
        onClick={() => setOpen(!open)}
      >
        <span
          style={{
            fontFamily: "'Baloo 2', sans-serif",
            fontWeight: 700,
            fontSize: "1rem",
            color: "var(--lf-dark)",
          }}
        >
          {q}
        </span>
        <ChevronDown
          size={20}
          className="flex-shrink-0 transition-transform duration-200"
          style={{ color: "var(--lf-teal)", transform: open ? "rotate(180deg)" : "rotate(0deg)" }}
        />
      </button>
      {open && (
        <div className="px-5 pb-5">
          <p style={{ color: "rgba(14,10,31,0.7)", fontSize: "0.95rem", lineHeight: 1.75 }}>{a}</p>
        </div>
      )}
    </div>
  );
}

export default function LearnPage() {
  return (
    <>
      <SiteHeader />
      <main style={{ background: "var(--lf-cream)" }}>
        {/* Hero */}
        <section
          className="pt-32 pb-12"
          style={{ background: "linear-gradient(160deg, var(--lf-cream) 0%, var(--lf-mint) 100%)" }}
        >
          <div className="mx-auto px-6 text-center" style={{ maxWidth: 680 }}>
            <Link
              href="/"
              className="inline-flex items-center gap-2 mb-6 text-sm font-semibold"
              style={{ color: "var(--lf-teal)" }}
            >
              <ArrowLeft size={15} /> Back to home
            </Link>
            <h1
              style={{
                fontFamily: "'Baloo 2', sans-serif",
                fontSize: "clamp(2.2rem, 5vw, 3.2rem)",
                fontWeight: 800,
                color: "var(--lf-dark)",
                lineHeight: 1.1,
              }}
            >
              Got questions?{" "}
              <span className="text-gradient-teal">We've got answers.</span>
            </h1>
            <p className="mt-4" style={{ color: "rgba(14,10,31,0.6)", fontSize: "1.05rem", lineHeight: 1.7 }}>
              Everything you need to know about Lalli Fafa — stories, personalisation, safety, and more.
            </p>
          </div>
        </section>

        {/* FAQ groups */}
        <section className="py-10 pb-16">
          <div className="mx-auto px-6" style={{ maxWidth: 780 }}>
            <div className="flex flex-col gap-12">
              {faqGroups.map((group) => (
                <div key={group.label}>
                  {/* Group label */}
                  <div className="flex items-center gap-3 mb-5">
                    <span
                      className="px-4 py-1.5 rounded-full text-sm font-bold uppercase tracking-wider"
                      style={{ background: group.bg, color: group.color }}
                    >
                      {group.label}
                    </span>
                    <div style={{ flex: 1, height: 1, background: "rgba(0,0,0,0.07)" }} />
                  </div>
                  <div className="flex flex-col gap-3">
                    {group.items.map((item, i) => (
                      <FAQItem key={i} q={item.q} a={item.a} />
                    ))}
                  </div>
                </div>
              ))}
            </div>

            {/* Still have questions? */}
            <div
              className="mt-14 rounded-3xl p-8 text-center flex flex-col items-center gap-4"
              style={{ background: "var(--lf-dark)" }}
            >
              <span style={{ fontSize: "2rem" }}>💬</span>
              <h2
                style={{
                  fontFamily: "'Baloo 2', sans-serif",
                  fontWeight: 800,
                  fontSize: "1.5rem",
                  color: "#fff",
                }}
              >
                Still have questions?
              </h2>
              <p style={{ color: "rgba(255,255,255,0.6)", fontSize: "0.95rem" }}>
                We're a small team and we read every message. Reach out and we'll get back to you.
              </p>
              <a
                href="mailto:hello@lallifafa.com"
                className="btn-primary"
                style={{ fontSize: "0.95rem" }}
              >
                <Sparkles size={15} />
                Email us
              </a>
            </div>
          </div>
        </section>
      </main>
      <SiteFooter />
    </>
  );
}
